theme: minima
title: Ms. Little if you're nasty!
author: CLittleTech
email: reachme@christina-little.com
description: > # this means to ignore newlines until "baseurl:"
  Just messing around. Nothing to see here. 

# social links
twitter_username: CLittleShelzi
github_username:  CLittleTech

show_excerpts: true # set to false to remove excerpts on the homepage
